#ifndef SYSTEM_CONFIG_H
#define SYSTEM_CONFIG_H


#define F_CPU 4000000UL
#define F_ADC_TARGET 250000UL  

#define USART_BAUDRATE 9600UL
#define USART_INSTANCE USART3  

#define ADC_VREF_VOLTAGE_mV 2048   
#define ADC_RESOLUTION_BITS 12     
#define ADC_MAX_VALUE ((1 << ADC_RESOLUTION_BITS) - 1)  

#define ADC_PRESCALER_FOR_250KHZ    ADC_PRESC_DIV16_gc

#define ADC_TEMP_INITDLY_CYCLES     32    
#define ADC_TEMP_SAMPLEN_CYCLES     120     

#define TEMP_SCALING_FACTOR         4096    
#define TEMP_KELVIN_TO_CELSIUS      273     

#define TEMPERATURE_READ_INTERVAL_MS 1000 

#endif